import { registerEnglishMessages } from './i18n'

export const qnapHostEnglishMessages: Record<string, string> = {
  '启用后，NAS 本机发起的 IPv4 公网流量和 IPv4 DNS 将优先经过 OpenSurge。QTS 主路由配置不会被修改。继续吗？': 'When enabled, IPv4 Internet traffic and IPv4 DNS generated by the NAS host will prefer OpenSurge. The QTS default-router configuration will not be changed. Continue?',
  'NAS 主机 IPv4 已通过 OpenSurge 接管。': 'NAS host IPv4 is now routed through OpenSurge.',
  'NAS 主机已恢复使用 QTS 原有路由。': 'The NAS host has returned to the original QTS routing.',
  'NAS 主机上网': 'NAS host Internet access',
  'NAS 主机路由切换失败': 'Failed to switch NAS host routing',
  '物理网卡、QNET、静态 IP、CIDR 与主路由在创建容器时确定；宿主机接管使用独立策略路由，不修改 QTS 保存的默认网关。': 'Physical NIC, QNET, static IP, CIDR, and upstream router are fixed when the container is created. NAS host takeover uses independent policy routing and does not change the default gateway stored by QTS.',
  '先执行安全清理；QNAP 版不会触碰宿主 QTS 保存的默认网关。': 'Run safe cleanup first. The QNAP build does not change the default gateway stored by QTS.',
  '一键让 QNAP 宿主机自己的 IPv4 流量通过 OpenSurge；QTS 默认网关仍保持原设置': 'Route IPv4 traffic generated by the QNAP host through OpenSurge with one switch while keeping the QTS default gateway unchanged.',
  'NAS 主机': 'NAS host',
  'OpenSurge 下一跳': 'OpenSurge next hop',
  'QTS 回退网关': 'QTS fallback gateway',
  'IPv4 DNS': 'IPv4 DNS',
  '已透明接管': 'Transparently redirected',
  '未接管': 'Not redirected',
  'NAS 主机接管已启用': 'NAS host takeover enabled',
  'NAS 主机接管正在等待网关就绪': 'NAS host takeover is waiting for the gateway',
  'NAS 主机接管未启用': 'NAS host takeover disabled',
  'NAS 本机产生的 IPv4 公网流量通过策略路由进入 OpenSurge；局域网、Docker 本地路由和 QTS 主路由配置保持原样。': 'IPv4 Internet traffic generated by the NAS host enters OpenSurge through policy routing. LAN routes, local Docker routes, and the QTS default-router configuration remain unchanged.',
  'OpenSurge 数据面恢复为 ready 后会自动重新接管；未就绪期间 NAS 使用 QTS 原有主路由。': 'Takeover is restored automatically when the OpenSurge data plane becomes ready. Until then, the NAS uses the original QTS default route.',
  '启用后只增加 OpenSurge 自己的宿主策略路由与 DNS 重定向，不会把 QTS GUI 的默认网关改成容器 IP。': 'Enabling adds only OpenSurge-owned host policy routes and DNS redirection; it does not change the QTS GUI default gateway to the container IP.',
  '当前容器缺少宿主网络接管能力': 'This container lacks NAS host takeover support',
  '请使用本版本的 Compose 重建一次容器；需要只读挂载宿主 network namespace，并只把 SYS_ADMIN 保留给 root Control 进程。': 'Recreate the container once with this version of the Compose file. It mounts the host network namespace read-only and keeps SYS_ADMIN only on the root Control process.',
  '正在切换…': 'Switching…',
  '停止 NAS 接管': 'Stop NAS takeover',
  '让 NAS 使用 OpenSurge': 'Use OpenSurge for NAS',
  '刷新状态': 'Refresh status',
  '此功能仅接管 NAS 宿主机本身产生的 IPv4 流量；IPv6 仍不由 OpenSurge 管理。容器正常停止或重建时会先释放宿主策略，避免 NAS 被留在失效的下一跳上。': 'This feature only takes over IPv4 traffic generated by the NAS host itself; IPv6 remains unmanaged by OpenSurge. On a normal container stop or rebuild, the host policy is released first so the NAS is not left pointing at a dead next hop.',
  '正在读取 NAS 主机路由能力…': 'Reading NAS host routing capability…',
}

registerEnglishMessages(qnapHostEnglishMessages)
